---

- name: postgres | setup yum repository
  become: true
  yum:
    name:
      https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: postgres | install client packages
  become: true
  yum:
    name:
      "{{ postgresql_client_redhat_basename[postgresql_client_version] }}"
    state: present
